set -sg escape-time 0
set -g status-interval 1
set-option -g renumber-windows on

set -g status-style 'bg=#cf5d06,fg=black'
set -g status-right "%I:%M %p, %d %b %Y"

# Set tmux to Vi mode
set-window-option -g mode-keys vi

# v for selection y for yanking
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
